name: ntaloventi

on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Session Setup
      uses: mxschmitt/action-tmate@master
